version: "3.4"

services:
    website:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "80:80"
          - "443:443"
        depends_on:
          - db

    db:
        image: "mcr.microsoft.com/mssql/server:latest"
        ports:
          - "1433:1433"

        environment:
            SA_PASSWORD: "S3cur3P@ssW0rd!"
            ACCEPT_EULA: "Y"